apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config
  namespace: arr
spec:
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 600Mi
  storageClassName: local-path
