apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: nextcloud
    name: nextcloud-data
  nfs:
    server: 192.168.10.199
    path: /tank/docs
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: nextcloud-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
