apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  DB_HOSTNAME: "192.168.10.158"
  DB_PORT: "5432"
  DB_DATABASE_NAME: "immich"
  DB_USERNAME: "immich"
  REDIS_HOSTNAME: "redis"
  REDIS_PORT: "6379"
  IMMICH_PORT: "2283"
