namespace: immich

resources:
  - namespace.yaml
  - redis
  - server

configMapGenerator:
  - name: immich-config
    envs:
      - ./config/immich.env

secretGenerator:
  - name: immich-secret
    envs: 
      - ./secrets/secrets.env
