apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 200Gi
  claimRef: 
    name: immich-data
    namespace: immich
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /tank/photos
    server: 192.168.10.199
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: immich
spec: 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: immich-data
  storageClassName: ""
