apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-nfs
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.10.199
    path: /tank/music/library

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: navidrome-nfs
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5G

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: navidrome-nfs-data
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 600M
